name = "gleamy_bench"
version = "0.5.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A library for benchmarking gleam code."
licences = ["Apache-2.0"]
repository = { type = "github", user = "schurhammer", repo = "gleamy_bench" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
